id: P000637
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4859
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་དམིགས་ཁྲིད་སྐྱོང་ཚུལ་མདོར་བསྡུས་ཐར་འདོད་འཇུག་ངོགས
  author: ''
  volumes:
    2471ec5846c54fa2bef04c190ce77765:
      image_group_id: I1KG5019
      title: ''
      volume_number: 1
      total_pages: 90
