id: I24FF8C82
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:26:26+00:00'
last_modified: '2022-06-07T12:31:43.245378+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4859
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་དམིགས་ཁྲིད་སྐྱོང་ཚུལ་མདོར་བསྡུས་ཐར་འདོད་འཇུག་ངོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1E43:
      image_group_id: I1KG5019
      title: ''
      total_pages: 90
      order: 1
      base_file: 1E43.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
